package Pos;


import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author walle
 */
public class SPAD extends javax.swing.JFrame {

    /**
     * Creates new form SPAD
     */
    public SPAD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnHeart = new javax.swing.JButton();
        jbtnButtors = new javax.swing.JButton();
        jbtnDark = new javax.swing.JButton();
        jbtnCabuary = new javax.swing.JButton();
        jbtnKitkat = new javax.swing.JButton();
        jbtnSnickers = new javax.swing.JButton();
        jbtnNoo = new javax.swing.JButton();
        jbtnChocolategarden = new javax.swing.JButton();
        jbtnDarkaine = new javax.swing.JButton();
        jbtnMaltes = new javax.swing.JButton();
        jbtnSenses = new javax.swing.JButton();
        jbtnRoses = new javax.swing.JButton();
        jbtnDublin = new javax.swing.JButton();
        jbtnShop = new javax.swing.JButton();
        jbtnAoife = new javax.swing.JButton();
        jbtnRocher = new javax.swing.JButton();
        jbtnMia = new javax.swing.JButton();
        jbtnRoyal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbtn9 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn111 = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jbtnPay = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtChange = new javax.swing.JTextField();
        jtxtDisplay = new javax.swing.JTextField();
        jcboPayment = new javax.swing.JComboBox<>();
        jtxtBarCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnHeart.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnHeart.setIcon(new javax.swing.ImageIcon("C:\\Users\\walle\\Downloads\\Video\\images5.jpg")); // NOI18N
        jbtnHeart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHeartActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnHeart, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 120, 130));

        jbtnButtors.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnButtors.setIcon(new javax.swing.ImageIcon("C:\\Users\\walle\\Downloads\\Video\\images.jpg")); // NOI18N
        jbtnButtors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnButtorsActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnButtors, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 130));

        jbtnDark.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnDark.setIcon(new javax.swing.ImageIcon("C:\\Users\\walle\\Downloads\\Video\\images4.jpg")); // NOI18N
        jbtnDark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDarkActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 120, 130));

        jbtnCabuary.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnCabuary.setIcon(new javax.swing.ImageIcon("C:\\Users\\walle\\Downloads\\Video\\images11.jpg")); // NOI18N
        jbtnCabuary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCabuaryActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCabuary, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 120, 130));

        jbtnKitkat.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnKitkat.setIcon(new javax.swing.ImageIcon("C:\\Users\\walle\\Downloads\\Video\\images10.jpg")); // NOI18N
        jbtnKitkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKitkatActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnKitkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 120, 130));

        jbtnSnickers.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnSnickers.setIcon(new javax.swing.ImageIcon("C:\\Users\\walle\\Downloads\\Video\\images8.jpg")); // NOI18N
        jbtnSnickers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSnickersActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSnickers, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 120, 130));

        jbtnNoo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnNoo.setIcon(new javax.swing.ImageIcon("C:\\Users\\walle\\Downloads\\Video\\images17.jpg")); // NOI18N
        jbtnNoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNooActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 120, 130));

        jbtnChocolategarden.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnChocolategarden.setIcon(new javax.swing.ImageIcon("C:\\Users\\walle\\Downloads\\Video\\images18.jpg")); // NOI18N
        jbtnChocolategarden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChocolategardenActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnChocolategarden, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 120, 130));

        jbtnDarkaine.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnDarkaine.setIcon(new javax.swing.ImageIcon("C:\\Users\\walle\\Downloads\\Video\\images15.jpg")); // NOI18N
        jbtnDarkaine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDarkaineActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDarkaine, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 120, 130));

        jbtnMaltes.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMaltes.setIcon(new javax.swing.ImageIcon("C:\\Users\\walle\\Downloads\\Video\\images14.jpg")); // NOI18N
        jbtnMaltes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMaltesActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnMaltes, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 120, 130));

        jbtnSenses.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnSenses.setIcon(new javax.swing.ImageIcon("C:\\Users\\walle\\Downloads\\Video\\images13.jpg")); // NOI18N
        jbtnSenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSensesActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSenses, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 120, 130));

        jbtnRoses.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnRoses.setIcon(new javax.swing.ImageIcon("C:\\Users\\walle\\Downloads\\Video\\images12.jpg")); // NOI18N
        jbtnRoses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRosesActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnRoses, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 120, 130));

        jbtnDublin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnDublin.setIcon(new javax.swing.ImageIcon("C:\\Users\\walle\\Downloads\\Video\\index20.jpg")); // NOI18N
        jbtnDublin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDublinActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDublin, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, 120, 130));

        jbtnShop.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnShop.setIcon(new javax.swing.ImageIcon("C:\\Users\\walle\\Downloads\\Video\\images23.jpg")); // NOI18N
        jbtnShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShopActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnShop, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 120, 130));

        jbtnAoife.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnAoife.setIcon(new javax.swing.ImageIcon("C:\\Users\\walle\\Downloads\\Video\\images22.jpg")); // NOI18N
        jbtnAoife.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAoifeActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAoife, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 120, 130));

        jbtnRocher.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnRocher.setIcon(new javax.swing.ImageIcon("C:\\Users\\walle\\Downloads\\Video\\images21.jpg")); // NOI18N
        jbtnRocher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRocherActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnRocher, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 120, 130));

        jbtnMia.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMia.setIcon(new javax.swing.ImageIcon("C:\\Users\\walle\\Downloads\\Video\\images19.jpg")); // NOI18N
        jbtnMia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMiaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnMia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 120, 130));

        jbtnRoyal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnRoyal.setIcon(new javax.swing.ImageIcon("C:\\Users\\walle\\Downloads\\Video\\images16.jpg")); // NOI18N
        jbtnRoyal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRoyalActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnRoyal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 120, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 790, 490));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 90, 90));

        jbtn7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 90));

        jbtn8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, 90));

        jbtn5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 90, 90));

        jbtn6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 90, 90));

        jbtn4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 90));

        jbtn2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 90, 90));

        jbtn3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 90, 90));

        jbtn1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 90, 90));

        jbtn111.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn111.setText(".");
        jbtn111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn111ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn111, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 90, 90));

        jbtnC.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 90, 90));

        jbtn0.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 90, 90));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 490));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 10, 300, 430));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnReset.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 210, 70));

        jbtnPay.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnPay.setText("Pay");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 210, 70));

        jbtnExit.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 420, 70));

        jbtnRemove.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 210, 70));

        jbtnPrint.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 210, 70));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 500, 440, 290));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Total");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Sub Total");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("Tax");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jtxtTotal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jPanel4.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 200, 50));

        jtxtSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jPanel4.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 200, 50));

        jtxtTax.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jPanel4.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 200, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 450, 290));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Change");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("Cash");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("Method");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jtxtChange.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jtxtChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChangeActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 200, 50));

        jtxtDisplay.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jPanel5.add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 200, 50));

        jcboPayment.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jcboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Visa Card", "Master Card", " " }));
        jPanel5.add(jcboPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 22, 200, 50));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 450, 290));
        getContentPane().add(jtxtBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 300, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    //==========================================Function=======================================
    
    public void ItemCost()
    {
        double sum = 0;
        for (int i =0; i < jTable1.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString() );
            
        }
        jtxtSubTotal.setText(Double.toString(sum));
        double cTotal1 = Double.parseDouble(jtxtSubTotal.getText());
        double cTax = (cTotal1 *3.9)/100;
        String iTaxTotal = String.format("€ %.2f", cTax);
        jtxtTax.setText(iTaxTotal);
        
        String iSubTotal = String.format("€ %.2f", cTotal1);
        jtxtSubTotal.setText(iSubTotal);
        
         String iTotal = String.format("€ %.2f", cTotal1 + cTax);
        jtxtTotal.setText(iTotal);
        
    }
    
    
    
    //==========================================Function Change=======================================
    
    public void Change()
    {
        double sum = 0;
        double tax = 3.9;
        double cash = Double.parseDouble(jtxtDisplay.getText());
        
        for (int i =0; i < jTable1.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString() );
            
        }
        
        double cTax = (sum *3.9)/100;
        double cChange = (cash - (sum+cTax));
        
        String ChangeGiven = String.format("€ %.2f", cChange);
        jtxtChange.setText(ChangeGiven);
        
        
    }
    
    
    
    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtChange.setText(jbtn7.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn7.getText();
             jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtChange.setText(jbtn8.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn8.getText();
             jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtChange.setText(jbtn9.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn9.getText();
             jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtChange.setText(jbtn4.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn4.getText();
             jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtChange.setText(jbtn5.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn5.getText();
             jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtChange.setText(jbtn6.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn6.getText();
             jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtChange.setText(jbtn1.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn1.getText();
             jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtChange.setText(jbtn2.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn2.getText();
             jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtChange.setText(jbtn3.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn3.getText();
             jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        if (Enternumber == "")
        {
            jtxtChange.setText(jbtn0.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn0.getText();
             jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        jtxtDisplay.setText("");
        jtxtChange.setText("");
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtn111ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn111ActionPerformed
        if (! jtxtDisplay.getText().contains(".")){
            jtxtDisplay.setText(jtxtDisplay.getText() + jbtn111.getText() );
            
        }
    }//GEN-LAST:event_jbtn111ActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
       if (jcboPayment.getSelectedItem().equals("Cash"))
       {
        Change();
        
       }
       else
       {
           jtxtChange.setText("");
           jtxtDisplay.setText("");
       }
       
    }//GEN-LAST:event_jbtnPayActionPerformed

    private void jbtnButtorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnButtorsActionPerformed
        double PriceofItem = 3.40;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Buttors Chocolate","1",PriceofItem});
        ItemCost();
    }//GEN-LAST:event_jbtnButtorsActionPerformed

    private void jbtnDarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDarkActionPerformed
        double PriceofItem = 2.90;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Dark Chocolate","1",PriceofItem});
        ItemCost();
    }//GEN-LAST:event_jbtnDarkActionPerformed

    private void jbtnHeartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHeartActionPerformed
        double PriceofItem = 2.78;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Heart Chocolate","1",PriceofItem});
        ItemCost();
    }//GEN-LAST:event_jbtnHeartActionPerformed

    private void jbtnSnickersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSnickersActionPerformed
        double PriceofItem = 2.57;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Snickers Chocolate","1",PriceofItem});
        ItemCost();
    }//GEN-LAST:event_jbtnSnickersActionPerformed

    private void jbtnKitkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKitkatActionPerformed
        double PriceofItem = 3.20;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Kitkat Chocolate","1",PriceofItem});
        ItemCost();
    }//GEN-LAST:event_jbtnKitkatActionPerformed

    private void jbtnCabuaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCabuaryActionPerformed
        double PriceofItem = 3.75;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Cabuary Milk Tray","1",PriceofItem});
        ItemCost();
    }//GEN-LAST:event_jbtnCabuaryActionPerformed

    private void jbtnRosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRosesActionPerformed
        double PriceofItem = 2.90;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Roses Chocolate","1",PriceofItem});
        ItemCost();
    }//GEN-LAST:event_jbtnRosesActionPerformed

    private void jbtnSensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSensesActionPerformed
        double PriceofItem = 2.90;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Senses Chocolate","1",PriceofItem});
        ItemCost();
    }//GEN-LAST:event_jbtnSensesActionPerformed

    private void jbtnMaltesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMaltesActionPerformed
        double PriceofItem = 3.40;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Maltes Chocolate","1",PriceofItem});
        ItemCost();
    }//GEN-LAST:event_jbtnMaltesActionPerformed

    private void jbtnDarkaineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDarkaineActionPerformed
        double PriceofItem = 3.95;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Dark Aine Chocolate","1",PriceofItem});
        ItemCost();
    }//GEN-LAST:event_jbtnDarkaineActionPerformed

    private void jbtnChocolategardenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChocolategardenActionPerformed
        double PriceofItem = 0.50;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Chocolate Garden","1",PriceofItem});
        ItemCost();
    }//GEN-LAST:event_jbtnChocolategardenActionPerformed

    private void jbtnNooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNooActionPerformed
        double PriceofItem = 2.10;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Noo Chocolate","1",PriceofItem});
        ItemCost();
    }//GEN-LAST:event_jbtnNooActionPerformed

    private void jbtnRoyalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRoyalActionPerformed
        double PriceofItem = 2.30;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Royal Chocolate","1",PriceofItem});
        ItemCost();
    }//GEN-LAST:event_jbtnRoyalActionPerformed

    private void jbtnMiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMiaActionPerformed
        double PriceofItem = 1.70;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Mia Chocolate","1",PriceofItem});
        ItemCost();
    }//GEN-LAST:event_jbtnMiaActionPerformed

    private void jbtnRocherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRocherActionPerformed
        double PriceofItem = 0.90;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Rocher Chocolate","1",PriceofItem});
        ItemCost();
    }//GEN-LAST:event_jbtnRocherActionPerformed

    private void jbtnAoifeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAoifeActionPerformed
        double PriceofItem = 0.80;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Aoife Chocolate","1",PriceofItem});
        ItemCost();
    }//GEN-LAST:event_jbtnAoifeActionPerformed

    private void jbtnShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShopActionPerformed
        double PriceofItem = 3.00;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Chocolate Shop","1",PriceofItem});
        ItemCost();
    }//GEN-LAST:event_jbtnShopActionPerformed

    private void jbtnDublinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDublinActionPerformed
        double PriceofItem = 0.15;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Dublin Chocolate","1",PriceofItem});
        ItemCost();
    }//GEN-LAST:event_jbtnDublinActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jtxtChange.setText("");
        jtxtTax.setText("");
        jtxtTotal.setText("");
        jtxtSubTotal.setText("");
        jtxtDisplay.setText("");
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        MessageFormat header = new MessageFormat("Payment Option " + jcboPayment.getSelectedItem().toString() + " SubTotal" + jtxtSubTotal.getText().toString() + " Tax" + jtxtTax.getText().toString() + " " + jtxtTotal.getText().toString());
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        
        try
        {
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
            
        }
        catch(java.awt.print.PrinterException e)
        {
             System.err.format ("No printer found", e.getMessage());
        }
        
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int RemoveItem = jTable1.getSelectedColumn();
        if(RemoveItem >= 0 )
        {
           model.removeRow(RemoveItem);
        }
        ItemCost();
        if (jcboPayment.getSelectedItem().equals("Cash"))
       {
        Change();
        
       }
       else
       {
           jtxtChange.setText("");
           jtxtDisplay.setText("");
       }
        
    }//GEN-LAST:event_jbtnRemoveActionPerformed

    private void jtxtChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChangeActionPerformed
private JFrame frame;

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
       
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit", "Point of Sale", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
            
    }//GEN-LAST:event_jbtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SPAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SPAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SPAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SPAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SPAD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn111;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnAoife;
    private javax.swing.JButton jbtnButtors;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnCabuary;
    private javax.swing.JButton jbtnChocolategarden;
    private javax.swing.JButton jbtnDark;
    private javax.swing.JButton jbtnDarkaine;
    private javax.swing.JButton jbtnDublin;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnHeart;
    private javax.swing.JButton jbtnKitkat;
    private javax.swing.JButton jbtnMaltes;
    private javax.swing.JButton jbtnMia;
    private javax.swing.JButton jbtnNoo;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnRocher;
    private javax.swing.JButton jbtnRoses;
    private javax.swing.JButton jbtnRoyal;
    private javax.swing.JButton jbtnSenses;
    private javax.swing.JButton jbtnShop;
    private javax.swing.JButton jbtnSnickers;
    private javax.swing.JComboBox<String> jcboPayment;
    private javax.swing.JTextField jtxtBarCode;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
